### ISSUE TITLE
Fix bug where "Loop current playback" doesn't work when set to Random.

### ISSUE THREAD

**Issue by noittaM** [libreofficecalc/BBCF-Improvement-Mod#37]
currently "Loop current playback" doesn't work at all when 'Playback type'(in game setting) is set to 'Random Playback'.

**Comment by libreofficecalc** [comment]
this is working as intended, the in-game setting is setting to 'Random Playback' there is no "current playback", since it is random. Probably should make it greyed out however when it is set.

**Comment by noittaM** [comment]
I thought that might be the intended, but I didn't find see a reason of it being like that. (aside from any technical reason)
is there some other way to loop random playbacks that I'm not seeing or is this something that's not easy to do with the current tools?

**Comment by libreofficecalc** [comment]
@noittaM  there is not unfortunately. It probably wouldn't be hard to add but its a matter of where to put it on the UI etc etc. Feel free to suggest or make a PR, should be just a case of randomly changing the slot when you reach the end of the current on.
