### ISSUE TITLE
Hitbox viewer and aspect ratio

### ISSUE THREAD

**Issue by MorphRed** [libreofficecalc/BBCF-Improvement-Mod#38]
The hitbox viewer does not accommodate for when keep aspect ratio is activated, as such the hitboxes are shifted when going to the sides
![Screenshot (552)](https://github.com/libreofficecalc/BBCF-Improvement-Mod/assets/111656218/12c317a5-ea97-46f0-9b78-ac322619126c)
![Screenshot (551)](https://github.com/libreofficecalc/BBCF-Improvement-Mod/assets/111656218/b6833fc1-90f1-4e56-87ad-9c74418f7e3c)

**Comment by MorphRed** [comment]
for info bb's aspect ratio is 5:3

**Comment by libreofficecalc** [comment]
is this at fullscreen?

**Comment by dupainsvp** [comment]
yes i am on fullscreen

**Comment by MorphRed** [comment]
> Seems to only happen at fullscreen, keep aspect ratio while windowed works fine.
yeah am on fullscreen

**Comment by MorphRed** [comment]
#45 Fixed with this
